### ISSUE TITLE
Compatibility?

### ISSUE THREAD

**Issue by Strovo** [ChafficPlugins/MiningLevels#5]
could it be used with a pickaxe created by mmoitems?

Will it work with custom blocks?

**Comment by Chafficui** [comment]
> could it be used with a pickaxe created by mmoitems?

It can be used with any item specified in the configs (in works over the material of the item)

> Will it work with custom blocks?

At the moment the plugin goes over the material, so it will work with every material that has the same material like your custom block.
I will work on supporting custom blocks and custom items.

**Comment by Chafficui** [comment]
I am sorry but it is not worth the time.
